export const reasons = [
  "Breaks Community rules",
  "Harassment",
  "Threatining violence",
  "Hate",
  "Minor abuse or sexualization",
  "Sharing personal information",
  "Non-consensual intimate media",
  "Prohebited transaction",
  "Impersonation",
  "Copyright violation",
  "Trademark violation",
  "Self-harm or suicide",
  "Spam",
];
